name: build

on:
  push:
    branches: [master]

jobs:
  go:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - name: Test
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          version: v1.52.2
